language: go
go:
  - 1.7
before_deploy:
  - go get -u gobot.io/x/gobot
  - go get -u github.com/laher/goxc
  - mkdir -p $TRAVIS_BUILD_DIR/dist
  - goxc -d=$TRAVIS_BUILD_DIR/dist -pv=$GENKAN_VERSION -arch=arm -os=linux -+tasks=clean,compile,archive xc -GOARM=6

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "1chqp+xFzhOaI3ulhltRjv4V4ANv2eeqS4Wr0zOW0uJl8SN2l2SMSbGNNKPa5PST4wtTNVQbbed1CixyuYs5Ak+EQuLMn6aoxzYaVDjsm81eaBLcwUx2IJTqmn6d7bzdAVLiY3I7c4PilbFY0FVau6PMauAE44YRKJ3Pf34hD4L+jaOzyUdrxM1osw4qb2ffrtFcQR/1My6P5yJRhi28atByMidiHY+Ay9+WHDFDDycdFINGZkJ7zYn0+z9Y+kDWGp/iIgAtxjVMlox2DwXBGA3Vk3QK7yDZ39YpqY2c++CAPfCIr21NI4w8F8Z5wK8wWGorcZPc6+t0CYNncpXXwsvJFd8tGVbo20Gmg8oqWVleVkDuxouw8q5VbICZ7+7VGvEs/X87P6s0neY4IigwmB4VjjIJOwge/RH7yI1g3XLI0J6GN+1cxuFpGc4cxwPmFaBdSzQJhGGp+q6ygFEWnZTwYXLSewJG7nPt1L5zEeVJ8wjEB2n4CpvDOJaGXioPZETukCdurG3GsA3pXUu+1aWuLasEYXsUEpMYL6CTa9z9cj91qA14CA1JD+6AErCRKO+OFbCDYd8HaooDB+Wf6BiWx7kKecpcBae7QefJe8CRSzWzfhLdH5ZbxHOZPsUS5xsmDnfceIWedlRNqa/YVXtY6TLLF8XSkZ54nyFI5sE="
  file:
    - dist/${GENKAN_VERSION}/genkan_device_${GENKAN_VERSION}_linux_arm.tar.gz
  on:
    tags: false
    branch: master

env:
  global:
    - GENKAN_VERSION: '0.0.2'
    # URI
    - secure: "CaldunJksO/w+GDluqgQ09xJUEsCgYS8W9P0RRFFnCsgga6EsNl28S8yFcXYNeiwE7HyafmSnbXL3cisO7AgycaM3knXKRboQfaqR0NGwXN6Vpe+vipV0kstI/I9ecC2fPIf7Q0nprjn8iXSbiVL9AUpjtuldB0B1XgNLeewh58ZSb4q1jEGML8PtJKHx52kZzhyYkp5DMSwMpZrzKYsK3ztuvus8HBK6U1JXN90OGqsV8pgy6gmloDWdK4QromTHdHqqlUyVBRnJPeP5DL/0eBbaFDi0ebYlqJdyD6zWS9Og4qJKn1dzjCOomBjJsKCyDkTr+KiBXR3bg+eyyqIhsJv/anA8T7OgKttvQ3qW8QvRvwRJXK1n+0pb8/TYa850usIzj5MffOTgjwVNFebubzxktvDn30iCDzbjhsoXZPsaWMJBESNHqYEhSt69puJyjfO81Ndsw4wdwBFFbEBHhGqtkdVQPaWuc6uVdPro5iltf3h4P339lw/h6anWEc1kySUefMgNLUjPhPdkByBZYz7wbs4maXriTjvj1woQIHAj+gHcr2diAKWJYCLbN8rkBxNjAnvxd9uebKDKshrLKNwg0zqg+ZlznKQep/V1O2j1wbdCkRYwdXewPl5EqlMwSL5UyPb98oYLCoVq6dWlMcUycS0tHVpMwj9HCnrfl0="
    # USERNAME
    - secure: "i2fGjPLl1adGj75UxrPhNFOoeeueCOpQiggG/vCb1cMZe/6JrDk4ae8Zl7/yy+S5w18NhK/sLciJiEvEPllglzRHfWMQWPkoiDV5UJ7pNKdbd6dsgDxSUkpS6x9t1gQ/5qnQhx2I/aIXiJwgo+KqbIUAbzrSxpl+Hi6Z8Pohy0KVD/y3yQSIvR6KPW2ASbkPUWC/KXHP+i5yp+tX2oqkPhiyR+jG+Z7DNq3oHLL7PcYZxgyMuOrvOQi28HLshQtkqDVuKoE8WNEDZnKxShNPRW0dm61RjK+0kVfjwGW3/RnwfpshjYsu02rhA8eDuiYtV7aqYw7PJT97nk0fg0S54L7maSGF/uEHwYtIZ5oHGMsyub50b19M34rq3evNoIcNHGruVkNLidW0DFb1LmTXDxY02a0wkIjYy4pbZJuxKpZLOoEeb9XlDHHY8DWZTb5hJ4iJPKwyYwSvfRYFYTgZxGVlipPX3d0nmaxk05ZcE//VSUyzMWMZmISNIxTvxY7E/zwP27e6hxb4z3YIzxsbNtMLE75fsOh4BcouD5swkJXw0+Crq64VETs+Iw0i2hWpxVnlyxtSL75ClhB6hQQcKIpAx6IqfoyhCKPX0khseo9ZoeCjM2gRLUaiQO+la4asRCpZfzQeg6uo9+SP7BsCVBBOeP9ftHLTSxFKr1lSJpM="
    # PASSWORD
    - secure: "djynXbpy9ho4Omu0abpVxBD6F9zAC6TkfG/zBEX1FciBqEALLrvluJtdjgwBD82Hm0fQvkxp4i9pkuo+96/df94ENPj4h1ZuRHPJ27RtR891ZzAIS5PMsDOxrnH006bY5b9mJGyRsISOAiKprqFdWgaGo4o3yMFZOJA/uCx7QUl568miBDDzee1JCKw6D3dnW1BifiX3abJoCn/ZoPClSzZXl+LPqoT4mkyCkEgoMtKg70cGz7BJy/K/hPaJzxC6jWya4YW9fRSIRo2Pve7Z+AXaV5Epq2Y/Zg8nezPMK36BNO99LBqA8BNfEtGpYBlHFidEGxB+60clDb/239CUHtdI0X3JeSw+JqXkddnrq/Ap3LdoB7SDVxPE9ncA093wfzS2RSaxauBpLsa8FmOIUVcY4TFxDVE8De9CBr9upg8bnpfNKmk22s9qlVsMHjmQaJElico1npH0yYeRfr9qIBLVgLWoWPnDTD57BW34ijLGLyEHJ3JD7B4za926iBr7sZZVT/+JQsGWTKvkld9AcEUX0iCWf3/mp3RmBa1Lv0Vrgk/SVx6jZYRDAwoNX41gnmo5vocWWGAre4t7zNPKM3H00d9D/dYwabg09MgEUh930OR1DssTvtDPPuXaoG2yK76VrWkzEDGqG1v28lG93uabij5T5hDulKwGHE0C3LU="
