language: go
go:
  - 1.7
before_deploy:
  - go get -u gobot.io/x/gobot
  - go get -u github.com/laher/goxc
  - mkdir -p $TRAVIS_BUILD_DIR/dist
  - goxc -d=$TRAVIS_BUILD_DIR/dist -pv=$GENKAN_VERSION -arch=arm -os=linux -+tasks=clean,compile,archive xc -GOARM=6

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "1chqp+xFzhOaI3ulhltRjv4V4ANv2eeqS4Wr0zOW0uJl8SN2l2SMSbGNNKPa5PST4wtTNVQbbed1CixyuYs5Ak+EQuLMn6aoxzYaVDjsm81eaBLcwUx2IJTqmn6d7bzdAVLiY3I7c4PilbFY0FVau6PMauAE44YRKJ3Pf34hD4L+jaOzyUdrxM1osw4qb2ffrtFcQR/1My6P5yJRhi28atByMidiHY+Ay9+WHDFDDycdFINGZkJ7zYn0+z9Y+kDWGp/iIgAtxjVMlox2DwXBGA3Vk3QK7yDZ39YpqY2c++CAPfCIr21NI4w8F8Z5wK8wWGorcZPc6+t0CYNncpXXwsvJFd8tGVbo20Gmg8oqWVleVkDuxouw8q5VbICZ7+7VGvEs/X87P6s0neY4IigwmB4VjjIJOwge/RH7yI1g3XLI0J6GN+1cxuFpGc4cxwPmFaBdSzQJhGGp+q6ygFEWnZTwYXLSewJG7nPt1L5zEeVJ8wjEB2n4CpvDOJaGXioPZETukCdurG3GsA3pXUu+1aWuLasEYXsUEpMYL6CTa9z9cj91qA14CA1JD+6AErCRKO+OFbCDYd8HaooDB+Wf6BiWx7kKecpcBae7QefJe8CRSzWzfhLdH5ZbxHOZPsUS5xsmDnfceIWedlRNqa/YVXtY6TLLF8XSkZ54nyFI5sE="
  file:
    - dist/${GENKAN_VERSION}/genkan_device_${GENKAN_VERSION}_linux_arm.tar.gz
  on:
    tags: true
    branch: master

after_deploy:
  - go build deployment/pushNewVersion.go
  - ./pushNewVersion $GENKAN_VERSION

env:
  global:
    - GENKAN_VERSION: '0.0.12'
    # URI
    - secure: "Qdelx7l7aErd1wHCfC3J/wq4dlMLOLmY36MdzHvq6kKMtijr7Mihc5PFpm1XI8FUu5Jox5QJqPufNgbfrUvJOCEZY+dS8d4ztGX5qL5LkQPPXcyCGaZwkqVcRbGXN+LL9WhDEERC7f3O2vV8KKRLmdlomST7dU7KcHjfxayIPPpLfeyVPB5byPOaRxV+0mtlkLnK9V+pqmpwc7czqDOrVJCT+/0avG5GLFozOOP3XztunGskRM+tRmtqhQx0rql6x0bKz5p+qufF+vPhhn+UJGVG7nr9T2VDkiknZNTLJ/y+86KyNampArxBfJ0E3hzLkPcEEctxPdD53mv7//ag/+Sze90Z8v2ufwg3+PIqEtxQz17Zqi6ygVLCjXQLPnkhaaB5u1opBvpLCsIZfsWXaSIGcAZUNO2qGZGxwmsIW0hAbZEK6tnAZUOo6bRMnlC5odSkRxU0FmZ6jy0ar+lHO3tIV2q9RSwGWix66v7GCL01gmjJZkZ1m+KKlFaivKYX8BJKbec0rnOhyAcdu6Wa7J7PeB/z26AMOgf4rL8zhhomHX2wfwyITtfeNljOxw1v/+TnUMZBa7IsOSCYXDuxolbHItkrhomtseSZFDjpFR5ypnB3CLagUKQi1mKvm6wYEKP/er2aR6hPM0fTschHKPReuG34Nh5r+qA/3lN5U8I="
    # USERNAME
    - secure: "u+1xByLJ8rXm544hkNKrr93LmoM108dEeRBK/xvRhRTShHC6ll8W+4CprvfsdmoA1jxkQBB/IbLScAG8gw41/VeqhgaKAxuM7c7yALSVG3t2TcNKOvdzXK8KzOR3wEnB0x0CBGTdK37ZgxofLVap1iKe2vWX2fT4Nc0V6eW4e3YeFPAdC+Tq7hunsqdrQtxPQW4mvf8LF4jHWNgvMzpds+yWV/lGkGyVPqZPEcH81uvhxrgPKSTA3zTXR4nPnRaHLBTGBhDZT/Q3qZY0QBoNJhxvdqEjSBChQ3fm0gjS5l3QSltNp3sQ62V/lZDS7tVUyn/55NTIAErjZ31w6iwLnflvx1eQ0TJIgl73mjFmMlQsVLlA0jLRg+7FsRVh14R+CoaW04paCLn1t83vVSnwLg1yXZ0M1czIq1ljEBD6vbKgcU09Dsw1nKJtJeDxrMStyWECBrYvPNeVib0K4gk0hrRq7jKrUiGN/5r4Wf44jsp2qZ31BEQUVGlKQ5iYQqHhvi0gLu/H26rcEZ60UrSi/h52z85y2g65VfYuzSg1xmJGGRu1KRz5I5VqdQxfYC/24tF5qjSRbIRwRv/AsRECtyL14sav0C/lW4DTypLhB8fHlRxwFn+hWRGtQgo73c/rdKYTxq/B2f0CsAwueVFwY+RoIIMFivHMRzp0j5cHC/g="
    # PASSWORD
    - secure: "iblwgEJ9Wre7u98NrpVuoesngPOQj1TVmD8G3LGY4mfDWNrvJ9gCeWkCHokG6ynEA5pzk+ClfsDsAlK5Ld7/lMiwXSs270xiU9BEZOaZ1zpIZWtzNu0dpkF6Nfcgsn3royA2WKDobGR1vkZGOikFSgCWs7ZpaKUc/hNGkoxwQowBhe1GmQr9bQh6orapBhjzd4dmAgT6N15np9CHQ3/HFC4+I9TfhYJFNmbsCtmFFRS3pHU4WvlnfAYzO4EvJIIJeF+waTZhIdYAZ2S69U3SNiI45aTxKLsGUrI5lGXMeNgivKjgMP+eiexG3w8bAk/TLjQ1ipb9edmY3qdRdOqXsZRqLttyaQ+DhfhJqMOiTZCQbaK/lw6DWKL8ADrkkIFxtajkmKUCxrhuQYdCUnHhY3sz9hOA8jXzz5ssLiXQrsxxHbScPQl9p/XgFIKkmIj53nz+kz7MwjACsRXLyaMOzA/O7MozgtnSjakwW6Rz+s+yco6WyVckbm0cdTbP1IWEOaqOOYK7/Wx0X3pqSLdCUmEtucoB/3VdQSb9hOlw9NDV7tnqVA5YY/CPRoqiYx9W/bntfcLmtVHaBkOafwhDtPuqRnStfSyeZMZq1SLR65+ISHFU5veYp9TeEFl5KPN2NrFf9469qMm0GwcbZUvNpCazgFtPk3Dh2L276uD68Cs="
